default: &default
  adapter: postgresql
  encoding: unicode
  username: 'admin'
  password: ''
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'smartflix_development'

test:
  <<: *default
  database: 'smartflix_test'

production:
  <<: *default
  database: 'smartflix_production'